### ISSUE TITLE
Cannot find module 'puppeteer'

### ISSUE THREAD

**Issue by D-Sketon** [zkz098/hexo-renderer-multi-next-markdown-it#7]
看了一眼依赖，好像把puppeteer换成了puppeteer-cn，但貌似hexo里puppeteer-cn没有自动下载puppeteer，还是说下载失败了？
![image](https://user-images.githubusercontent.com/49871906/214497384-7b90684c-5016-49a0-a576-1fc49697a248.png)

**Comment by D-Sketon** [comment]
还有mermaid并不能成功加载（Shoka中的老问题了），具体可以看看https://blog.liq2.com/article/ff29002e

**Comment by zkz098** [comment]
应该是puppeteer-cn下载依赖失败了,但是原因未知

**Comment by zkz098** [comment]
puppeteer-cn访问的chrome-driver路径404了,所以cnpm也没法安装

**Comment by zkz098** [comment]
很奇怪的一个事：
从npmmirror复制的链接长这样：
`https://registry.npmmirror.com/-/binary/chromedriver/110.0.5481.30/chromedriver_win32.zip` (200)
而从cnpm和puppeteer-cn得到的链接都长这样：
`https://cdn.npmmirror.com/binaries/chromium-browser-snapshots/Win_x64/1083080/chrome-win.zip` (404)
🤔

**Comment by zkz098** [comment]
应该是storage.googleapis.com目录改版了,npmmirror还没同步
目前https://storage.googleapis.com直接访问速度挺快的,先改回原版puppeteer

**Comment by zkz098** [comment]
![image](https://user-images.githubusercontent.com/92242020/214511353-8fd89667-c8ee-431d-b376-497926975c31.png)
0.1.6已修复
